name: SimplifiedCommands
version: 1.0
author: Ice
main: ice.and.snow.bukkit.commands.MainPlugin

commands:
  chest: 
    description: En simplere version af kommandoerne fra 'Virtual Chest'
    usage: /chest [kiste-navn|[stoerrelse kiste-navn]]
  gethead: 
    description: En unik kommando, som giver en spiler en spillers hoved
    usage: /gethead [navn]